version: '3.3'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge 
    volumes:
      - ~/sql-server/data:/var/opt/mssql/data
      - ~/sql-server/log:/var/opt/mssql/log
      - ~/sql-server/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - 1433:1433
    networks:
      - project-manage

  server:
    build:
      context: ./project-management-server/
      dockerfile: ./Dockerfile
      target: dev
    image: gin1111/project-management-server:dev
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - project-manage
      - back-end
    volumes:
      - type: bind
        source: ./project-management-server/
        target: /server
      - type: volume
        target: /server/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  client:
    build:
      context: ./project-management-client/
      dockerfile: ./Dockerfile
      target: dev
    image: gin1111/project-manage-client:dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./project-management-client/
        target: /client
      - type: volume
        target: /client/node_modules
    networks:
      - back-end
    restart: unless-stopped

networks:
  project-manage:
  back-end:
